var MOMONDO_URL = "http://www.momondo.ca";
var MOMONDO_FLIGHT_SEARCH_URL = MOMONDO_URL + "/flightsearch?Search=True";
var MOMONDO_FLIGHTS_SEARCH_URL_SEARCH_QUERY_SUFFIX = "&TK=ECO&DO=false&NA=false";

module.exports = {
	MOMONDO_FLIGHT_SEARCH_URL : MOMONDO_FLIGHT_SEARCH_URL,
	MOMONDO_FLIGHTS_SEARCH_URL_SEARCH_QUERY_SUFFIX : MOMONDO_FLIGHTS_SEARCH_URL_SEARCH_QUERY_SUFFIX
}